### ISSUE TITLE
Torrent link requires registration

### ISSUE THREAD

**Issue by Meyermagic** [ozonos/ozonos.github.io#13]
Attempting to download the torrent link leads to the following message:

> Access to 'Ozon-Hydrogen-Beta.iso.torrent' is limited due to high download traffic. 
> The content of this link is available only for pCloud users at the moment.

The file is only 21KB, so I suggest hosting it on GitHub, or elsewhere without a click-through before the download.

**Comment by Meyermagic** [comment]
Or even use a magnet link, hosting the torrent with the swarm.

**Comment by loctauxphilippe** [comment]
Ok I'll do it

**Comment by loctauxphilippe** [comment]
it's done now
