### ISSUE TITLE
Questions from a windows noobie

### ISSUE THREAD

**Issue by TheSevenDev** [ozonos/ozonos.github.io#16]
Hello, I've been keeping my eyes on this distribution for quite some time and I'm really interested in giving it a try BUT I have some questions about it and I hope someone can help me here.
Bear in mind that I've worked with almost 0 experience with Linux whatsoever.

- Does this dist. require some experience with Linux in order to use it properly?
- What are the "performance optimizations" it delivers specifically?
- Which games/software have been reported to not work atm?
- Is using the terminal required?

Thanks in advance, keep up the good work!﻿

**Comment by UriHerrera** [comment]
- No unless you do something that's specifically done in Linux like using commands.
- There aren't any yet.
- We don't have any particular database of any game working or not working. Games that work on Linux should work on all Linux distributions unless they specifically target one distribution but that's up to the game developers.
- No unless the GUI method doesn't work.

**Comment by TheSevenDev** [comment]
Do I need Wine to play older games?

**Comment by UriHerrera** [comment]
DOS era games require a DOS emulator like DOSBox, newer games are likely to be supported by Wine still WineHQ should be consulted beforehand as there are instructions for games that don't install and run out of the box.

**Comment by TheSevenDev** [comment]
Is there anyway to emulate the OS virtually? I've seen that VirtualBox doesn't work well with it yet.

**Comment by UriHerrera** [comment]
Neither Virtualbox nor Vmware which are the most user-friendly options are suited for gaming. Unless you really want to you could use Qemu or KVM otherwise you're going to have to keep Windows in dual boot or only use the games that can run with Wine (those rated platinum and gold) or that are native to Linux.

**Comment by TheSevenDev** [comment]
I might try the dual boot, thanks a lot!
