### ISSUE TITLE
Website doesn't work when cloned locally

### ISSUE THREAD

**Issue by GizmoCodes** [ozonos/ozonos.github.io#19]
I like the look of the Ozon OS Website, but when cloning it, it seems to not work. I have installed Sass and Lace. I thought it looked like a Jekyll theme, but when trying to do ```jekyll serve``` it throws [this](http://pastebin.com/dwvt0uwQ). Heres what It looks like currently:

![image](https://cloud.githubusercontent.com/assets/10952522/10776513/269ea9ac-7ce0-11e5-94db-27c46bd45dbc.png)

If this is intended to be an site you can't clone then just say and close the issue.

 - Ta,
     Gizmo

**Comment by loctauxphilippe** [comment]
@GizmoCodes Hey, I just cloned with `git clone https://github.com/ozonos/ozonos.github.io.git --recursive`, `cd` into the folder and run `jekyll serve`, opened my browser at `localhost:4000` and I got this result.

![screenshot from 2015-10-28 18-25-44](https://cloud.githubusercontent.com/assets/8809909/10797139/871e5e64-7da1-11e5-926c-6e2fe9dec5dd.png)

It works, so you may check what's wrong

**Comment by GizmoCodes** [comment]
Heh, it seems I forgot the `--recursive`. Sorry for wasting peoples time!

**Comment by loctauxphilippe** [comment]
You didn't wasted my time!
