### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by loctauxphilippe** [ozonos/ozonos.github.io#2]
![ozon](https://cloud.githubusercontent.com/assets/8809909/5398843/f7b840ce-8165-11e4-90fe-abeaa3a13ef1.png)
I think you should create a favicon for the website... The Google's one isn't very nice for this page...

**Comment by loctauxphilippe** [comment]
You can generate yours on http://realfavicongenerator.net/

**Comment by satya164** [comment]
I need a better quality ozon logo, @me4oslav ?

**Comment by me4oslav** [comment]
@satya164 @loctauxphilippe there is a 16x16 svg file:
https://my.pcloud.com/publink/show?code=XZ31xkZefLlmMjHhCB0cXWab5Xi9YqFJtSy
You figure out how to implement it. :P

**Comment by loctauxphilippe** [comment]
@me4oslav No problem sir

**Comment by me4oslav** [comment]
16*32 = 512. Open wit with gimp, set size to 512 and ta.

**Comment by loctauxphilippe** [comment]
@me4oslav I added the favicons. But I need @satya164 to implement them (since I don't know how to do that with jekyll

**Comment by me4oslav** [comment]
The issue is now gone. Closing it.
