### ISSUE TITLE
Links for icons

### ISSUE THREAD

**Issue by loctauxphilippe** [ozonos/ozonos.github.io#4]
You should add links for Numix and Nitrux's logos. And maybe add a colored version when the mouse is on the icon...

**Comment by Foggalong** [comment]
The coloured version on highlight is a cool idea!

**Comment by loctauxphilippe** [comment]
@Foggalong You're welcome!

**Comment by loctauxphilippe** [comment]
I can't do it for you for the moment, but I found something that may help you! http://www.corelangs.com/css/box/hover.html

**Comment by satya164** [comment]
We could put colored images instead of grey ones, and add a grayscale filter, then remove the filter on hover.

But what should be the color of the nitrux logo?

**Comment by UriHerrera** [comment]
It's dark gray, so ideally both logos when on hover would use a lighter gray.

**Comment by Foggalong** [comment]
Ahhh, in was forgetting that the Nitrux logo doesn't have colour

**Comment by me4oslav** [comment]
Wait, isn't the desired behaviour:
normal - light grey
on hover - dark grey / nitrux, red - numix
?

**Comment by loctauxphilippe** [comment]
@me4oslav Yes it should be like this

**Comment by me4oslav** [comment]
Well, somebody implement it.

**Comment by satya164** [comment]
Nitrux logo being monochrome and numix logo being colorful is lots of inconsistency.

**Comment by me4oslav** [comment]
But is is how the logos are. I take it, we can not make @UriHerrera make the nitrux one blue or something.

**Comment by satya164** [comment]
That's why we cannot make numix logo red here. It's fine with grey, I think.

**Comment by cldx** [comment]
Imho, it's really simple, both Icons get the same hover color (if any), it should be the same hover/focus color used elsewhere on the site, f.e. The download button color...and links should maybe use that too? Just my 2 cents.

**Comment by UriHerrera** [comment]
I guess @cldx solution is the best.

**Comment by me4oslav** [comment]
So:
normal state - grey.
hover state - teal.
Right?

**Comment by UriHerrera** [comment]
Yeah.

**Comment by me4oslav** [comment]
Okies. Are the light grey and dark grey logos images or just the light grey are and the dark grey are CSS coloured? I might be able to fix that.

**Comment by loctauxphilippe** [comment]
@me4oslav It's the CSS

**Comment by me4oslav** [comment]
@loctauxphilippe Damn. Somebody implement it, then.

**Comment by loctauxphilippe** [comment]
@me4oslav I'll try to do it a day or another

**Comment by loctauxphilippe** [comment]
I don't have the pics, I can't do it

**Comment by me4oslav** [comment]
Te pics are in source. /assets/logo*.

**Comment by loctauxphilippe** [comment]
Someone need to recolor them: #11aa89 for both. both versions
Them give me them, and I'll implement them.

**Comment by me4oslav** [comment]
I need the .svg version for both to do that. Recolouring raster one is painful. 
@satya164 @UriHerrera Can you guys provide me with svg versions?

**Comment by loctauxphilippe** [comment]
@me4oslav Than give me them and I'll implement them.

**Comment by me4oslav** [comment]
Aye, I know. :)

**Comment by loctauxphilippe** [comment]
The branch have been deleted now, I'll wait for the svgs and I'll implement them

**Comment by GizmoCodes** [comment]
I added one recently [here](https://github.com/ozonos/ozon-wiki/wiki/Installation-Instructions), but the site isn't updated yet.
