### ISSUE TITLE
Adding Google+ profile to the footer

### ISSUE THREAD

**Issue by aleksandar-todorovic** [ozonos/ozonos.github.io#8]
Since this project is pretty active on Google+, I thought that you should probably add a link to it to the footer section (since GitHub and Twitter profiles are already there).

I have already forked the repository and made needed changes locally, but before I submit a pull request, I would need to know about that `<path>` tag. I thought that these icons were imported from [FontAwesome](http://fortawesome.github.io/Font-Awesome/) but it turns out that they are not imported in a standard way.

Could you help me a bit to add that path correctly so I could create my pull request?

**Comment by loctauxphilippe** [comment]
@me4oslav should be able to do that

**Comment by me4oslav** [comment]
This is for @satya164.

**Comment by me4oslav** [comment]
Fixed it just now. Even added fb too. Closing the issue.
